import AppKit
import CryptoKit
import Foundation

struct CapturedClipboardItem: Sendable {
    let type: ClipboardItemType
    let capturedAt: Date = Date()
    let preview: String
    let searchIndex: String?
    let thumbnailPNGData: Data?
    let encryptedPayload: EncryptedClipboardPayload?
    let digest: String
    let byteSize: Int
    let sourceBundleIdentifier: String?
}

@MainActor
final class ClipboardCaptureService {
    var onCapture: ((CapturedClipboardItem) -> Void)?
    var onSensitiveContentSkipped: (() -> Void)?
    var onExcludedApplicationSkipped: (() -> Void)?

    private let pasteboard: NSPasteboard
    private let settings: SettingsStore
    private let sourceBundleIdentifierProvider: () -> String?

    private var timer: Timer?
    private var lastChangeCount: Int
    private var digestToIgnoreOnce: String?
    private var pendingImageOCRDigests = Set<String>()
    private var captureGeneration = 0

    private let maxPayloadBytes = 2_000_000
    private let maxTextCharacters = 20_000
    private let maxSearchIndexCharacters = 800
    private let concealedPasteboardType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private let autoGeneratedPasteboardType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private let imageOCRService = ImageOCRService()

    var isMonitoringEnabled = true {
        didSet {
            guard isMonitoringEnabled != oldValue else {
                return
            }

            resetPasteboardBaseline()
        }
    }

    init(
        pasteboard: NSPasteboard = .general,
        settings: SettingsStore,
        sourceBundleIdentifierProvider: @escaping () -> String? = {
            NSWorkspace.shared.frontmostApplication?.bundleIdentifier?.lowercased()
        }
    ) {
        self.pasteboard = pasteboard
        self.settings = settings
        self.sourceBundleIdentifierProvider = sourceBundleIdentifierProvider
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        schedulePollingTimer()
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func applySettings() {
        schedulePollingTimer()
    }

    func resetPasteboardBaseline() {
        lastChangeCount = pasteboard.changeCount
        digestToIgnoreOnce = nil
        pendingImageOCRDigests.removeAll()
        captureGeneration += 1
    }

    @discardableResult
    func writeToPasteboard(item: ClipboardHistoryItem) -> Bool {
        var expectedDigestToIgnore: String?
        let payload = item.decryptedPayload()

        switch item.type {
        case .text, .url:
            if let text = payload?.plainText {
                if writeStringToPasteboard(text) {
                    expectedDigestToIgnore = digest(data: Data(text.utf8))
                }
            }
        case .image:
            if let data = payload?.imagePNGData {
                // Keep exact PNG bytes to avoid re-encoding drift that would break deduplication.
                pasteboard.clearContents()
                if pasteboard.setData(data, forType: .png) {
                    expectedDigestToIgnore = digest(data: data)
                }
            }
        case .file:
            let urls = (payload?.filePaths ?? []).map { URL(fileURLWithPath: $0) as NSURL }
            if !urls.isEmpty {
                pasteboard.clearContents()
                if pasteboard.writeObjects(urls) {
                    let joined = urls
                        .map { ($0 as URL).path }
                        .joined(separator: "\n")
                    expectedDigestToIgnore = digest(data: Data(joined.utf8))
                }
            }
        }

        digestToIgnoreOnce = expectedDigestToIgnore
        return expectedDigestToIgnore != nil
    }

    @discardableResult
    func writePlainTextToPasteboard(item: ClipboardHistoryItem) -> Bool {
        guard let text = plainTextRepresentation(for: item) else {
            return false
        }

        guard writeStringToPasteboard(text) else {
            return false
        }

        digestToIgnoreOnce = digest(data: Data(text.utf8))
        return true
    }

    @discardableResult
    func writeString(_ text: String) -> Bool {
        guard writeStringToPasteboard(text) else {
            return false
        }

        digestToIgnoreOnce = digest(data: Data(text.utf8))
        return true
    }

    private func schedulePollingTimer() {
        timer?.invalidate()

        let interval = settings.pollInterval
        let newTimer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.pollPasteboard()
            }
        }
        newTimer.tolerance = min(0.2, interval * 0.25)

        RunLoop.main.add(newTimer, forMode: .common)
        timer = newTimer
    }

    func pollPasteboard() {
        guard isMonitoringEnabled else {
            return
        }

        let newChangeCount = pasteboard.changeCount
        guard newChangeCount != lastChangeCount else {
            return
        }

        lastChangeCount = newChangeCount

        let pasteboardTypes = pasteboard.types?.map(\.rawValue) ?? []
        let ignoredDigest = digestToIgnoreOnce
        digestToIgnoreOnce = nil
        if ignoredDigest != nil,
           SensitiveContentDetector.shouldBlock(pasteboardTypes: pasteboardTypes)
        {
            return
        }

        guard let capture = readCapture() else {
            return
        }

        if ignoredDigest == capture.digest {
            return
        }

        if shouldDeferImageCaptureForOCR(capture),
           let pngData = imagePNGData(for: capture)
        {
            deferImageCaptureUntilOCRCompletes(capture, pngData: pngData)
            return
        }

        onCapture?(capture)
    }

    func readCapture() -> CapturedClipboardItem? {
        let sourceBundleIdentifier = sourceBundleIdentifierProvider()?.lowercased()
        if let sourceBundleIdentifier,
           settings.excludedBundleIdentifiers.contains(sourceBundleIdentifier)
        {
            onExcludedApplicationSkipped?()
            return nil
        }

        let captureRule = settings.appCaptureRule(for: sourceBundleIdentifier)
        if captureRule?.ignoresCapture == true {
            onExcludedApplicationSkipped?()
            return nil
        }

        let pasteboardTypes = pasteboard.types?.map(\.rawValue) ?? []
        if SensitiveContentDetector.shouldBlock(pasteboardTypes: pasteboardTypes) {
            onSensitiveContentSkipped?()
            return nil
        }

        if captureRule?.textOnly != true,
           settings.captureFiles,
           let fileCapture = readFileCapture(sourceBundleIdentifier: sourceBundleIdentifier)
        {
            return fileCapture
        }

        if let textCapture = readTextCapture(sourceBundleIdentifier: sourceBundleIdentifier) {
            return textCapture
        }

        if captureRule?.textOnly != true,
           settings.captureImages,
           let imageCapture = readImageCapture(sourceBundleIdentifier: sourceBundleIdentifier)
        {
            return imageCapture
        }

        return nil
    }

    private func readTextCapture(sourceBundleIdentifier: String?) -> CapturedClipboardItem? {
        guard let rawText = pasteboard.string(forType: .string) ?? pasteboard.string(forType: .URL) else {
            return nil
        }

        let sanitized = rawText
            .replacingOccurrences(of: "\u{0000}", with: "")

        let trimmedForValidation = sanitized.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedForValidation.isEmpty else {
            return nil
        }

        if settings.filterSensitiveContent, SensitiveContentDetector.shouldBlock(text: sanitized) {
            onSensitiveContentSkipped?()
            return nil
        }

        let textToStore = String(sanitized.prefix(maxTextCharacters))
        guard !textToStore.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return nil
        }

        let data = Data(textToStore.utf8)
        guard data.count <= maxPayloadBytes else {
            return nil
        }

        let type: ClipboardItemType
        let trimmedForClassification = textToStore.trimmingCharacters(in: .whitespacesAndNewlines)
        if let url = URL(string: trimmedForClassification), url.scheme != nil {
            type = .url
        } else {
            type = .text
        }

        let preview = textPreview(for: textToStore, type: type)
        let payload = ClipboardItemPayload(
            plainText: textToStore,
            imagePNGData: nil,
            filePaths: nil
        )
        guard let encryptedPayload = try? EncryptedClipboardPayload.seal(payload) else {
            return nil
        }

        return CapturedClipboardItem(
            type: type,
            preview: preview,
            searchIndex: sourceApplicationSearchIndex(sourceBundleIdentifier),
            thumbnailPNGData: nil,
            encryptedPayload: encryptedPayload,
            digest: digest(data: data),
            byteSize: data.count,
            sourceBundleIdentifier: sourceBundleIdentifier
        )
    }

    private func readFileCapture(sourceBundleIdentifier: String?) -> CapturedClipboardItem? {
        guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL], !urls.isEmpty else {
            return nil
        }

        let normalizedPaths = urls
            .filter(\.isFileURL)
            .map(\.path)
            .filter { !$0.isEmpty }
            .prefix(30)

        guard !normalizedPaths.isEmpty else {
            return nil
        }

        let paths = Array(normalizedPaths)
        if settings.filterSensitiveContent && paths.contains(where: SensitiveContentDetector.shouldBlock(filePath:)) {
            onSensitiveContentSkipped?()
            return nil
        }

        let joined = paths.joined(separator: "\n")
        let data = Data(joined.utf8)

        guard data.count <= maxPayloadBytes else {
            return nil
        }

        let preview: String
        if paths.count == 1 {
            preview = URL(fileURLWithPath: paths[0]).lastPathComponent
        } else {
            preview = "\(paths.count) files"
        }

        let payload = ClipboardItemPayload(
            plainText: nil,
            imagePNGData: nil,
            filePaths: paths
        )
        guard let encryptedPayload = try? EncryptedClipboardPayload.seal(payload) else {
            return nil
        }

        let searchablePaths = paths
            .map { URL(fileURLWithPath: $0).lastPathComponent }
            .joined(separator: " ")

        return CapturedClipboardItem(
            type: .file,
            preview: preview,
            searchIndex: makeSearchIndex(
                preview: preview,
                sourceBundleIdentifier: sourceBundleIdentifier,
                additionalTerms: [searchablePaths]
            ),
            thumbnailPNGData: nil,
            encryptedPayload: encryptedPayload,
            digest: digest(data: data),
            byteSize: data.count,
            sourceBundleIdentifier: sourceBundleIdentifier
        )
    }

    private func readImageCapture(sourceBundleIdentifier: String?) -> CapturedClipboardItem? {
        let imageData = pasteboard.data(forType: .png) ?? {
            guard let tiffData = pasteboard.data(forType: .tiff), let image = NSImage(data: tiffData) else {
                return nil
            }
            return image.coparePNGData()
        }()

        guard let pngData = imageData else {
            return nil
        }

        guard pngData.count <= maxPayloadBytes else {
            return nil
        }

        guard let image = NSImage(data: pngData) else {
            return nil
        }

        let size = image.size
        let preview = "Image \(Int(size.width))x\(Int(size.height))"
        let payload = ClipboardItemPayload(
            plainText: nil,
            imagePNGData: pngData,
            filePaths: nil
        )
        guard let encryptedPayload = try? EncryptedClipboardPayload.seal(payload) else {
            return nil
        }

        return CapturedClipboardItem(
            type: .image,
            preview: preview,
            searchIndex: makeSearchIndex(
                preview: preview,
                sourceBundleIdentifier: sourceBundleIdentifier
            ),
            thumbnailPNGData: ClipboardHistoryItem.makeThumbnailPNGData(from: pngData),
            encryptedPayload: encryptedPayload,
            digest: digest(data: pngData),
            byteSize: pngData.count,
            sourceBundleIdentifier: sourceBundleIdentifier
        )
    }

    private func makeSearchIndex(
        preview: String,
        sourceBundleIdentifier: String?,
        additionalTerms: [String] = []
    ) -> String? {
        var components = [preview]

        if let sourceBundleIdentifier {
            components.append(sourceBundleIdentifier)
            if let appName = SourceApplicationResolver.displayName(for: sourceBundleIdentifier) {
                components.append(appName)
            }
        }

        components.append(contentsOf: additionalTerms)
        let merged = components
            .joined(separator: " ")
            .condensingWhitespace()
        guard !merged.isEmpty else {
            return nil
        }

        return String(merged.prefix(maxSearchIndexCharacters))
    }

    private func shouldDeferImageCaptureForOCR(_ capture: CapturedClipboardItem) -> Bool {
        capture.type == .image && settings.imageOCRIndexingEnabled && settings.filterSensitiveContent
    }

    private func imagePNGData(for capture: CapturedClipboardItem) -> Data? {
        guard let encryptedPayload = capture.encryptedPayload else {
            return nil
        }

        return (try? encryptedPayload.open())?.imagePNGData
    }

    private func deferImageCaptureUntilOCRCompletes(_ capture: CapturedClipboardItem, pngData: Data) {
        guard pendingImageOCRDigests.insert(capture.digest).inserted else {
            return
        }

        let imageOCRService = imageOCRService
        let generation = captureGeneration
        Task.detached(priority: .utility) { [weak self] in
            let ocrText = imageOCRService.recognizedText(fromPNGData: pngData)
            let shouldBlock = ocrText.map { SensitiveContentDetector.shouldBlock(text: $0) } ?? false

            await self?.completeDeferredImageCapture(
                capture,
                generation: generation,
                shouldBlock: shouldBlock
            )
        }
    }

    private func completeDeferredImageCapture(
        _ capture: CapturedClipboardItem,
        generation: Int,
        shouldBlock: Bool
    ) {
        guard generation == captureGeneration else {
            return
        }

        pendingImageOCRDigests.remove(capture.digest)

        guard isMonitoringEnabled, settings.captureImages else {
            return
        }

        if let sourceBundleIdentifier = capture.sourceBundleIdentifier {
            let captureRule = settings.appCaptureRule(for: sourceBundleIdentifier)
            if settings.excludedBundleIdentifiers.contains(sourceBundleIdentifier)
                || captureRule?.ignoresCapture == true
                || captureRule?.textOnly == true
            {
                onExcludedApplicationSkipped?()
                return
            }
        }

        if shouldBlock, settings.filterSensitiveContent {
            onSensitiveContentSkipped?()
            return
        }

        onCapture?(capture)
    }

    private func plainTextRepresentation(for item: ClipboardHistoryItem) -> String? {
        let payload = item.decryptedPayload()
        switch item.type {
        case .text, .url:
            return payload?.plainText
        case .file:
            guard let filePaths = payload?.filePaths, !filePaths.isEmpty else {
                return nil
            }
            return filePaths.joined(separator: "\n")
        case .image:
            return nil
        }
    }

    private func textPreview(for text: String, type: ClipboardItemType) -> String {
        if SensitiveContentDetector.shouldMaskPreview(text: text) {
            return type == .url ? "Sensitive URL hidden" : "Sensitive text hidden"
        }
        return text.previewSnippet()
    }

    private func sourceApplicationSearchIndex(_ sourceBundleIdentifier: String?) -> String? {
        guard let sourceBundleIdentifier else {
            return nil
        }

        var terms = [sourceBundleIdentifier]
        if let appName = SourceApplicationResolver.displayName(for: sourceBundleIdentifier) {
            terms.append(appName)
        }

        let merged = terms.joined(separator: " ").condensingWhitespace()
        guard !merged.isEmpty else {
            return nil
        }

        return String(merged.prefix(maxSearchIndexCharacters))
    }

    private func writeStringToPasteboard(_ text: String) -> Bool {
        let pasteboardItem = NSPasteboardItem()
        pasteboardItem.setString(text, forType: .string)
        pasteboardItem.setData(Data(), forType: concealedPasteboardType)
        pasteboardItem.setData(Data(), forType: autoGeneratedPasteboardType)
        pasteboard.clearContents()
        return pasteboard.writeObjects([pasteboardItem])
    }

    private func digest(data: Data) -> String {
        let hash = SHA256.hash(data: data)
        return hash.map { String(format: "%02x", $0) }.joined()
    }

}

private extension NSImage {
    func coparePNGData() -> Data? {
        guard let tiffData = tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiffData)
        else {
            return nil
        }

        return bitmap.representation(using: .png, properties: [:])
    }
}
