import Foundation

enum SensitiveContentDetector {
    private static let keywords = [
        "password",
        "passwd",
        "otp",
        "2fa",
        "totp",
        "api key",
        "secret",
        "private key",
        "bearer ",
        "session token",
    ]

    private static let protectedPasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "de.petermaurer.concealedPasteboard",
    ]

    private static let protectedPasteboardHints = [
        "concealed",
        "autogenerated",
        "onepassword",
        "1password",
        "bitwarden",
        "lastpass",
        "keepass",
        "keepassxc",
        "protonpass",
        "dashlane",
        "enpass",
        "strongbox",
    ]

    private static let blockedFileExtensions: Set<String> = [
        "asc",
        "crt",
        "der",
        "env",
        "envrc",
        "key",
        "kdbx",
        "kubeconfig",
        "npmrc",
        "ovpn",
        "pem",
        "pub",
        "pfx",
        "p12",
        "tfstate",
        "tfvars",
    ]

    private static let blockedFileNames: Set<String> = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.development",
        ".npmrc",
        ".pypirc",
        ".netrc",
        "credentials",
        "id_rsa",
        "id_dsa",
        "id_ecdsa",
        "id_ed25519",
    ]

    private static let blockedPathHints = [
        "/.ssh/",
        "/.gnupg/",
        "/.aws/credentials",
        "/.aws/config",
        "/.kube/config",
        "/.docker/config.json",
        "/.config/gcloud/application_default_credentials.json",
        "/.terraform.d/credentials.tfrc.json",
        "/library/application support/1password",
        "/library/application support/bitwarden",
    ]

    static func shouldBlock(text: String) -> Bool {
        let normalized = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard normalized.count >= 6 else {
            return false
        }

        let lowercased = normalized.lowercased()
        if keywords.contains(where: { lowercased.contains($0) }) {
            return true
        }

        if normalized.range(
            of: #"^eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$"#,
            options: .regularExpression
        ) != nil {
            return true
        }

        if normalized.range(
            of: #"(?i)(sk_live|ghp_|xox[baprs]-|AKIA)[A-Za-z0-9_\-]{10,}"#,
            options: .regularExpression
        ) != nil {
            return true
        }

        if normalized.range(
            of: #"(?i)-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"#,
            options: .regularExpression
        ) != nil {
            return true
        }

        if normalized.range(
            of: #"^[A-Za-z0-9+/_\-]{32,}={0,2}$"#,
            options: .regularExpression
        ) != nil {
            return true
        }

        if normalized.range(of: #"^\d{6}$"#, options: .regularExpression) != nil {
            return true
        }

        return false
    }

    static func shouldBlock(filePath: String) -> Bool {
        let normalized = filePath.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.isEmpty else {
            return false
        }

        let lowercased = normalized.lowercased()
        let url = URL(fileURLWithPath: normalized)
        let fileExtension = url.pathExtension.lowercased()
        let fileName = url.lastPathComponent.lowercased()

        if blockedFileExtensions.contains(fileExtension) {
            return true
        }

        if blockedFileNames.contains(fileName) || fileName.hasPrefix(".env.") {
            return true
        }

        if blockedPathHints.contains(where: lowercased.contains) {
            return true
        }

        return false
    }

    static func shouldBlock(pasteboardTypes: [String]) -> Bool {
        guard !pasteboardTypes.isEmpty else {
            return false
        }

        if pasteboardTypes.contains(where: protectedPasteboardTypes.contains) {
            return true
        }

        return pasteboardTypes.contains { type in
            let lowercased = type.lowercased()
            return protectedPasteboardHints.contains(where: lowercased.contains)
        }
    }
}
