import Foundation

enum SensitiveContentDetector {
    private nonisolated static let keywords = [
        "password",
        "passwd",
        "passphrase",
        "otp",
        "2fa",
        "totp",
        "api key",
        "secret",
        "client_secret",
        "refresh_token",
        "private key",
        "bearer ",
        "session token",
    ]

    private nonisolated static let protectedPasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "de.petermaurer.concealedPasteboard",
    ]

    private nonisolated static let protectedPasteboardHints = [
        "concealed",
        "autogenerated",
        "onepassword",
        "1password",
        "bitwarden",
        "lastpass",
        "keepass",
        "keepassxc",
        "protonpass",
        "dashlane",
        "enpass",
        "strongbox",
    ]

    private nonisolated static let blockedFileExtensions: Set<String> = [
        "asc",
        "crt",
        "der",
        "env",
        "envrc",
        "key",
        "kdbx",
        "kubeconfig",
        "npmrc",
        "ovpn",
        "pem",
        "pub",
        "pfx",
        "p12",
        "tfstate",
        "tfvars",
    ]

    private nonisolated static let blockedFileNames: Set<String> = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.development",
        ".npmrc",
        ".pypirc",
        ".netrc",
        "credentials",
        "id_rsa",
        "id_dsa",
        "id_ecdsa",
        "id_ed25519",
    ]

    private nonisolated static let blockedPathHints = [
        "/.ssh/",
        "/.gnupg/",
        "/.aws/credentials",
        "/.aws/config",
        "/.kube/config",
        "/.docker/config.json",
        "/.config/gcloud/application_default_credentials.json",
        "/.terraform.d/credentials.tfrc.json",
        "/library/application support/1password",
        "/library/application support/bitwarden",
    ]

    private nonisolated static let sensitiveURLQueryKeys: Set<String> = [
        "access_token",
        "api_key",
        "apikey",
        "auth",
        "authorization",
        "client_secret",
        "code",
        "id_token",
        "key",
        "refresh_token",
        "secret",
        "sig",
        "signature",
        "token",
        "x-amz-credential",
        "x-amz-security-token",
        "x-amz-signature",
        "x-goog-credential",
        "x-goog-signature",
    ]

    nonisolated static func shouldBlock(text: String) -> Bool {
        let normalized = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard normalized.count >= 6 else {
            return false
        }

        let lowercased = normalized.lowercased()
        if keywords.contains(where: { lowercased.contains($0) }) {
            return true
        }

        if containsSensitiveURLCredential(in: normalized) {
            return true
        }

        if normalized.range(
            of: #"(?<![A-Za-z0-9_-])eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}(?![A-Za-z0-9_-])"#,
            options: .regularExpression
        ) != nil {
            return true
        }

        if normalized.range(
            of: #"(?i)(sk_live|ghp_|gho_|ghu_|github_pat_|xox[baprs]-|xoxe-|AKIA|ASIA|A3T|AGPA|AIDA|AROA|AIPA|ANPA|ANVA)[A-Za-z0-9_\-]{10,}"#,
            options: .regularExpression
        ) != nil {
            return true
        }

        if normalized.range(
            of: #"(?<![A-Za-z0-9])([MN][A-Za-z0-9]{23}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27,})(?![A-Za-z0-9])"#,
            options: .regularExpression
        ) != nil {
            return true
        }

        if normalized.range(
            of: #"(?i)-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"#,
            options: .regularExpression
        ) != nil {
            return true
        }

        if normalized.range(
            of: #"(?i)-----BEGIN PGP PRIVATE KEY BLOCK-----"#,
            options: .regularExpression
        ) != nil {
            return true
        }

        if normalized.range(
            of: #"^[A-Za-z0-9+/_\-]{32,}={0,2}$"#,
            options: .regularExpression
        ) != nil {
            return true
        }

        if normalized.range(of: #"^\d{6}$"#, options: .regularExpression) != nil {
            return true
        }

        return false
    }

    nonisolated static func shouldMaskPreview(text: String) -> Bool {
        let normalized = text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .condensingWhitespace()

        guard !normalized.isEmpty else {
            return false
        }

        if shouldBlock(text: normalized) {
            return true
        }

        if normalized.contains("://") {
            return containsSensitiveURLCredential(in: normalized)
        }

        if normalized.contains(" ") {
            return false
        }

        if normalized.count >= 24,
           normalized.range(of: #"^[A-Za-z0-9+/_=\-]{24,}$"#, options: .regularExpression) != nil
        {
            return true
        }

        let entropy = shannonEntropy(of: normalized)
        if normalized.count >= 16 && entropy >= 3.7 {
            return true
        }

        let classes = characterClassCount(in: normalized)
        if normalized.count >= 14 && classes >= 3 {
            return true
        }

        return false
    }

    private nonisolated static func containsSensitiveURLCredential(in text: String) -> Bool {
        let candidates = text
            .components(separatedBy: .whitespacesAndNewlines)
            .map { $0.trimmingCharacters(in: CharacterSet(charactersIn: "<>()[]{}\"'`,")) }
            .filter { $0.contains("://") }

        return candidates.contains(where: urlContainsSensitiveCredential)
    }

    private nonisolated static func urlContainsSensitiveCredential(_ rawURL: String) -> Bool {
        guard let components = URLComponents(string: rawURL),
              components.scheme != nil
        else {
            return false
        }

        if let password = components.password, !password.isEmpty {
            return true
        }

        if let user = components.user, isLikelySecretURLValue(user) {
            return true
        }

        return (components.queryItems ?? []).contains { item in
            sensitiveURLQueryKeys.contains(item.name.lowercased()) &&
                isLikelySecretURLValue(item.value ?? "")
        }
    }

    private nonisolated static func isLikelySecretURLValue(_ value: String) -> Bool {
        let normalized = value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard normalized.count >= 12 else {
            return false
        }

        if normalized.range(of: #"^[A-Za-z0-9+/_=.\-:%]+$"#, options: .regularExpression) != nil {
            return true
        }

        return normalized.count >= 24
    }

    nonisolated static func shouldBlock(filePath: String) -> Bool {
        let normalized = filePath.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.isEmpty else {
            return false
        }

        let originalURL = URL(fileURLWithPath: normalized).standardizedFileURL
        let resolvedURL = originalURL.resolvingSymlinksInPath().standardizedFileURL
        let urlsToCheck = [originalURL, resolvedURL]
        let pathsToCheck = urlsToCheck.map { $0.path.lowercased() }

        for url in urlsToCheck {
            let fileExtension = url.pathExtension.lowercased()
            let fileName = url.lastPathComponent.lowercased()

            if blockedFileExtensions.contains(fileExtension) {
                return true
            }

            if blockedFileNames.contains(fileName) || fileName.hasPrefix(".env.") {
                return true
            }
        }

        if blockedPathHints.contains(where: { hint in
            pathsToCheck.contains(where: { $0.contains(hint) })
        }) {
            return true
        }

        return false
    }

    nonisolated static func shouldBlock(pasteboardTypes: [String]) -> Bool {
        guard !pasteboardTypes.isEmpty else {
            return false
        }

        if pasteboardTypes.contains(where: protectedPasteboardTypes.contains) {
            return true
        }

        return pasteboardTypes.contains { type in
            let lowercased = type.lowercased()
            return protectedPasteboardHints.contains(where: lowercased.contains)
        }
    }

    private nonisolated static func characterClassCount(in value: String) -> Int {
        var count = 0
        if value.rangeOfCharacter(from: .lowercaseLetters) != nil {
            count += 1
        }
        if value.rangeOfCharacter(from: .uppercaseLetters) != nil {
            count += 1
        }
        if value.rangeOfCharacter(from: .decimalDigits) != nil {
            count += 1
        }

        let symbolSet = CharacterSet.alphanumerics.inverted
        if value.rangeOfCharacter(from: symbolSet) != nil {
            count += 1
        }
        return count
    }

    private nonisolated static func shannonEntropy(of value: String) -> Double {
        guard !value.isEmpty else {
            return 0
        }

        var frequencies: [Character: Double] = [:]
        for character in value {
            frequencies[character, default: 0] += 1
        }

        let length = Double(value.count)
        var entropy = 0.0
        for frequency in frequencies.values {
            let probability = frequency / length
            entropy -= probability * log2(probability)
        }
        return entropy
    }
}
